backend/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('/',[\App\Http\Controllers\LandingController::class,'tags']);

Route::post('/select/tags',[\App\Http\Controllers\LandingController::class,'selectTags'])->name('selectTags');
Route::get('/recom',[\App\Http\Controllers\LandingController::class,'index'])->where('slug', '^[\w-]+$')->name('index');
Route::get('/',[\App\Http\Controllers\LandingController::class,'biasa'])->name('biasa');
Route::get('/detail/{id}/{slug}',[\App\Http\Controllers\LandingController::class,'show'])->name('show');

Auth::routes();

Route::group(['prefix'=>'admin/ganteng/','as'=>'admin.'],function (){
    Route::middleware([])->group(function () {
        Route::get('home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

        Route::resource('tags', \App\Http\Controllers\Admin\TagController::class);
        Route::get('tags/{id}/destroy', [\App\Http\Controllers\Admin\TagController::class,'destroy'])->name('tagsDestroy');

        Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
        Route::get('categories/{id}/destroy', [\App\Http\Controllers\Admin\CategoryController::class,'destroy'])->name('categoriesDestroy');

        Route::resource('ukm', \App\Http\Controllers\Admin\UkmController::class);
        Route::get('ukm/{id}/destroy', [\App\Http\Controllers\Admin\UkmController::class,'destroy'])->name('ukmDestroy');
//        Route::resource('staff', \App\Http\Controllers\Admin\StaffController::class);

        Route::get('staff/{id}', [\App\Http\Controllers\Admin\StaffController::class,'create'])->name('staff.create');
        Route::post('staff/{id}', [\App\Http\Controllers\Admin\StaffController::class,'store'])->name('staff.store');
        Route::get('staff/{idUKM}/{idStaff}', [\App\Http\Controllers\Admin\StaffController::class,'destroy'])->name('staff.destroy');


        Route::get('ukm/galleries/{id}', [\App\Http\Controllers\Admin\GalleryController::class,'index'])->name('galleries.index');
        Route::post('ukm/galleries/{id}/create', [\App\Http\Controllers\Admin\GalleryController::class,'create'])->name('galleries.create');
        Route::post('ukm/galleries/thumbnail', [\App\Http\Controllers\Admin\GalleryController::class,'image'])->name('galleries.thumbnail');
        Route::delete('ukm/galleries/selectDelete', [\App\Http\Controllers\Admin\GalleryController::class,'selectDelete'])->name('galleries.selectDelete');

    });
}
);

backend/resources/views/admin/layouts/partials/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
        Copyright &copy; 2018 <div class="bullet"></div> Design By <a href="https://nauval.in/">Muhamad Nauval Azhar</a>
    </div>
    <div class="footer-right">
        2.3.0
    </div>
</footer>

backend/resources/views/admin/layouts/partials/notice.blade.php
@if (session('success'))
    <div class="alert alert-success">
        <p>{{ session('success') }}</p>
    </div>
@elseif(session('danger'))
    <div class="alert alert-danger">
        <p>{{ session('danger') }}</p>
    </div>
@elseif(session('warning'))
    <div class="alert alert-warning">
        <p>{{ session('warning') }}</p>
    </div>
@endif

backend/resources/views/admin/layouts/partials/sidebar.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="index.html">Stisla</a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="index.html">St</a>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">Dashboard</li>
            <li class="nav-item dropdown active">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-fire"></i><span>Dashboard</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="index-0.html">General Dashboard</a></li>
                    <li class="active"><a class="nav-link" href="index.html">Ecommerce Dashboard</a></li>
                </ul>
            </li>
            <li class="menu-header">Item</li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-columns"></i> <span>UKM</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{route('admin.ukm.index')}}">UKM</a></li>
                    <li><a class="nav-link" href="layout-default.html">Regis Ketua UKM</a></li>
                    <li><a class="nav-link" href="{{route('admin.categories.index')}}">Category Ukm</a></li>
                    <li><a class="nav-link" href="{{route('admin.tags.index')}}">Tags Ukm</a></li>

                </ul>
            </li>

        </ul>
    </aside>
</div>