backend/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('/',[\App\Http\Controllers\LandingController::class,'tags']);

Route::post('/select/tags',[\App\Http\Controllers\LandingController::class,'selectTags'])->name('selectTags');
Route::get('/recom',[\App\Http\Controllers\LandingController::class,'index'])->where('slug', '^[\w-]+$')->name('index');
Route::get('/',[\App\Http\Controllers\LandingController::class,'biasa'])->name('biasa');
Route::get('/detail/{id}/{slug}',[\App\Http\Controllers\LandingController::class,'show'])->name('show');

Auth::routes();

Route::group(['prefix'=>'admin/ganteng/','as'=>'admin.'],function (){
    Route::middleware([])->group(function () {
        Route::get('home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

        Route::resource('tags', \App\Http\Controllers\Admin\TagController::class);
        Route::get('tags/{id}/destroy', [\App\Http\Controllers\Admin\TagController::class,'destroy'])->name('tagsDestroy');

        Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
        Route::get('categories/{id}/destroy', [\App\Http\Controllers\Admin\CategoryController::class,'destroy'])->name('categoriesDestroy');

        Route::resource('ukm', \App\Http\Controllers\Admin\UkmController::class);
        Route::get('ukm/{id}/destroy', [\App\Http\Controllers\Admin\UkmController::class,'destroy'])->name('ukmDestroy');
//        Route::resource('staff', \App\Http\Controllers\Admin\StaffController::class);

        Route::get('staff/{id}', [\App\Http\Controllers\Admin\StaffController::class,'create'])->name('staff.create');
        Route::post('staff/{id}', [\App\Http\Controllers\Admin\StaffController::class,'store'])->name('staff.store');
        Route::get('staff/{idUKM}/{idStaff}', [\App\Http\Controllers\Admin\StaffController::class,'destroy'])->name('staff.destroy');


        Route::get('ukm/galleries/{id}', [\App\Http\Controllers\Admin\GalleryController::class,'index'])->name('galleries.index');
        Route::post('ukm/galleries/{id}/create', [\App\Http\Controllers\Admin\GalleryController::class,'create'])->name('galleries.create');
        Route::post('ukm/galleries/thumbnail', [\App\Http\Controllers\Admin\GalleryController::class,'image'])->name('galleries.thumbnail');
        Route::delete('ukm/galleries/selectDelete', [\App\Http\Controllers\Admin\GalleryController::class,'selectDelete'])->name('galleries.selectDelete');

    });
}
);

backend/app/Models/Staff.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Staff extends Model
{
    use HasFactory;

    public function ukm(){
        return $this->belongsToMany(Staff::class,'staff_ukms');
    }
}

backend/app/Models/Ukm.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ukm extends Model
{
    use HasFactory;


    public function tags(){
        return $this->belongsToMany(Tag::class,'ukm_tags','ukm_id','tag_id');
    }

    public function ukmTags(){
        return $this->hasMany(UkmTag::class);
    }

    public function categories(){
        return $this->belongsTo(Category::class,'category_id');

    }

    public function images(){
        return $this->hasMany(Image::class);
    }


    public function staffs(){
        return $this->belongsToMany(Staff::class,'staff_ukms','ukm_id','staff_id');
    }
}

backend/app/Http/Controllers/Admin/StaffController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Periode;
use App\Models\Staff;
use App\Models\StaffUkm;
use App\Models\Ukm;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        $data = Ukm::find($id);

        view()->share([
           'id' => $id,
            'data' => $data
        ]);

        return view('admin.dashboard.ukm.staff.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $id)
    {

        $dataCount = count($request->role);

//        dd($request->name);
        $validates = [
            'start_date' => 'required',
            'end_date' => 'required'
        ];

        $request->validate($validates);

        $periode = new Periode();
        $periode->start_date = $request->start_date;
        $periode->end_date = $request->end_date;
        $periode->save();

        for ($i =0 ; $i<$dataCount;$i++){

            if ($request->role[$i] == null || $request->name[$i] == null){
                return redirect()->back()->with('warning','there is an empty field');
            }

            $data = new Staff();
            $data->role = $request->role[$i];
            $data->name = $request->name[$i];
            $data->save();

            $staffUkm = new StaffUkm();
            $staffUkm->ukm_id = $id;
            $staffUkm->staff_id = $data->id;
            $staffUkm->periode_id = $periode->id;

            $staffUkm->save();
        }
        $ukm = Ukm::find($id);
        $ukm->final = '1';

        $ukm->save();

        return redirect()->route('admin.ukm.index')->with('success','success add UKM');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($idUKM,$idStaff)
    {
        $data = StaffUkm::where([
            'ukm_id' => $idUKM,
            'staff_id' => $idStaff
        ])->delete();

        $staff = Staff::find($idStaff);
        $staff->delete();

        return redirect()->back();

    }
}

backend/app/Http/Controllers/Admin/UkmController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Image;
use App\Models\Tag;
use App\Models\Ukm;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\DataTables;

class UkmController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    function check()
    {
        $userId = Auth::user()->id;
        $data = Ukm::whereUsersId($userId)->whereFinal('0')->first();

        return $data;
    }

    public function index(Request $request)
    {

        if($request->ajax()) {
//        $data = Item::orderBy('created_at','DESC')->get();
            if (Auth::user()->role_id == 2)
            {
                $data = Ukm::whereUsersId(Auth::user()->id)->whereFinal('1')->get();

            }else{
                $data = Ukm::whereFinal('1')->orderBy('updated_at','DESC')->get();

            }

//        dd($data);
            return DataTables::of($data)->addColumn('name', function($data){
                $a = '<a href="'.route('admin.galleries.index',$data->id).'">'.$data->name.'</a>';
                return $a;
                })
                ->addColumn('category_id', function($data){
                    $a = $data->categories->name;
                    return $a;
                })
                ->addColumn('action', function($data){
                    $button = '<a href="ukm/'.$data->id.'/edit'.'" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>';
                    $button .= '<a  href="'.route('admin.ukmDestroy',$data->id).'" class="btn btn-danger" onclick="return confirm('.'`Are you sure?`'.')"><i class="fa fa-trash"></i> Delete</a>';
                    return $button;
                })
                ->rawColumns(['name','category_id','action'])
                ->make(true);
        }
        return view('admin.dashboard.ukm.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::all();
        $categories = Category::all();
        $data = $this->check();

        view()->share([
            'tags' => $tags,
            'categories' => $categories,
            'data' => $data
        ]);
        return view('admin.dashboard.ukm.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $this->check();

        $validates = [
            'name'      => 'required',
            'category_id'=> 'required',
            'tag'=> 'required',
            'schedule'=> 'required',
            'benefit'=> 'required',
            'vision'=> 'required',
            'dsc'       => 'required',

        ];
        $request->validate($validates);

        if ($data == null ){
            $data = new Ukm();
            $file = $request->file('image');

            $name = rand(999999,1);
            $extension = $file->getClientOriginalExtension();
            $newName = $name.'.'.$extension;
//                $path = $request->file('image')->storeAs('public',$newName);
            Storage::putFileAs('public',$file,$newName);

            $imgDB = 'storage/'.$newName;
            $data->logo = $imgDB;
        }else{
            $data->logo = $request->newImage;
        }

        $data->category_id = $request->category_id;
        $data->users_id = Auth::user()->id;
        $data->name = $request->name;
        $data->slug = \Str::slug($request->name);
        $data->schedule = $request->schedule;
        $data->benefit = $request->benefit;
        $data->vision = $request->vision;
        $data->mission = $request->mission;
        $data->dsc = $request->dsc;
        $data->final = '0';



        $data->save();

        $tags = $request->tag;
        $data->tags()->sync($tags);

        return redirect()->route('admin.staff.create',$data->id);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id,Request $request)
    {
        $data = Ukm::findOrFail($id);
        $categories = Category::all();
        $tags = Tag::all();


        view()->share([
            'data' => $data,
            'categories' => $categories,
            'tags' => $tags,
        ]);
        return view('admin.dashboard.ukm.edit');

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Ukm::findOrFail($id);

        $validates = [
            'name'      => 'required',
            'category_id'=> 'required',
            'tag'=> 'required',
            'schedule'=> 'required',
            'benefit'=> 'required',
            'vision'=> 'required',
            'dsc'       => 'required',

        ];
        $request->validate($validates);

        if ($data == null ){
            $file = $request->file('image');

            $name = rand(999999,1);
            $extension = $file->getClientOriginalExtension();
            $newName = $name.'.'.$extension;
//                $path = $request->file('image')->storeAs('public',$newName);
            Storage::putFileAs('public',$file,$newName);

            $imgDB = 'storage/'.$newName;
            $data->logo = $imgDB;
        }else{
            $data->logo = $request->newImage;
        }


        $data->category_id = $request->category_id;
        $data->users_id = Auth::user()->id;
        $data->name = $request->name;
        $data->slug = \Str::slug($request->name);
        $data->schedule = $request->schedule;
        $data->benefit = $request->benefit;
        $data->vision = $request->vision;
        $data->mission = $request->mission;
        $data->dsc = $request->dsc;
        $data->final = '1';



        $data->save();

        $tags = $request->tag;
        $data->tags()->sync($tags);


        return redirect()->route('admin.ukm.index')->with('success','success add UKM');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $data = Ukm::findOrFail($id);
            $data->delete();
            return redirect()->route('admin.ukm.index')->with('danger','delete UKM success');

        }catch (\Exception $e){
//            return $e->getMessage();
            return redirect()->back()->with('warning','cant delete this data bcs  : ' . $e->getMessage());
        }


    }
}

backend/resources/views/admin/dashboard/ukm/staff/create.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>UKM</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="#">Modules</a></div>
                    <div class="breadcrumb-item">DataTables</div>
                </div>
            </div>
            @include('admin.layouts.partials.notice')

            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="container">
                                <div class="d-flex justify-content-between pt-5">
                                    <div>
                                        <h4>Structure UKM</h4>
                                    </div>
                                </div>
                            </div>

                            <div class="card-body">
                                <form action="{{route('admin.staff.store',$id)}}" method="post" enctype="multipart/form-data">
                                    @csrf
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3 ">Peridode </label>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Start Date</label>
                                        <div class="col-sm-6 col-md-7">
                                            <input type="date" name="start_date" class="form-control @error('title') is-invalid @enderror">
                                            @error('start_date')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">End Date</label>
                                        <div class="col-sm-6 col-md-7">
                                            <input type="date" name="end_date" class="form-control @error('title') is-invalid @enderror">
                                            @error('end_date')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <br><br>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Data Staff</label>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Role</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="role[]" class="form-control @error('title') is-invalid @enderror">
                                            @error('role')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Name</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="name[]" class="form-control @error('title') is-invalid @enderror">
                                            @error('name')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="staff">

                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            <a style="color: white" class="btn btn-success float-right addstaff">New Staff</a>
                                        </div>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            @if($data->final == '0')
                                                <a href="{{route('admin.ukm.create')}}" style="color: white" class="btn btn-primary">Back</a>
                                            @endif
                                            <button class="btn btn-primary">Finish</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script>
        $('.addstaff').on('click',function (){
            addstaff();
        });
        function addstaff(){
            var staff = '<div class="form-group row mb-4"> <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Data Staff</label> </div><div class="form-group row mb-4"> <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Role</label> <div class="col-sm-12 col-md-7"> <input type="text" name="role[]" id="role" class="form-control @error('title') is-invalid @enderror"> @error('name') <div class="alert alert-danger">{{ $message }}</div> @enderror </div> </div> <div class="form-group row mb-4"> <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Name</label> <div class="col-sm-12 col-md-7"> <input type="text" name="name[]" id="name" class="form-control @error('title') is-invalid @enderror"> @error('name') <div class="alert alert-danger">{{ $message }}</div> @enderror </div> </div><div class="form-group row mb-4"> <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label> <div class="col-sm-12 col-md-7"> <a style="color: white" class="btn btn-danger float-right remove">Remove</a></div></div>';

            $('.staff').append(staff);
        };
        $('.remove').live('click', function(){
            $(this).parent().parent().parent().remove();
        });
    </script>
@endsection