backend/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('/',[\App\Http\Controllers\LandingController::class,'tags']);

Route::post('/select/tags',[\App\Http\Controllers\LandingController::class,'selectTags'])->name('selectTags');
Route::get('/recom',[\App\Http\Controllers\LandingController::class,'index'])->where('slug', '^[\w-]+$')->name('index');
Route::get('/',[\App\Http\Controllers\LandingController::class,'biasa'])->name('biasa');
Route::get('/detail/{id}/{slug}',[\App\Http\Controllers\LandingController::class,'show'])->name('show');

Auth::routes();

Route::group(['prefix'=>'admin/ganteng/','as'=>'admin.'],function (){
    Route::middleware([])->group(function () {
        Route::get('home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

        Route::resource('tags', \App\Http\Controllers\Admin\TagController::class);
        Route::get('tags/{id}/destroy', [\App\Http\Controllers\Admin\TagController::class,'destroy'])->name('tagsDestroy');

        Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
        Route::get('categories/{id}/destroy', [\App\Http\Controllers\Admin\CategoryController::class,'destroy'])->name('categoriesDestroy');

        Route::resource('ukm', \App\Http\Controllers\Admin\UkmController::class);
        Route::get('ukm/{id}/destroy', [\App\Http\Controllers\Admin\UkmController::class,'destroy'])->name('ukmDestroy');
//        Route::resource('staff', \App\Http\Controllers\Admin\StaffController::class);

        Route::get('staff/{id}', [\App\Http\Controllers\Admin\StaffController::class,'create'])->name('staff.create');
        Route::post('staff/{id}', [\App\Http\Controllers\Admin\StaffController::class,'store'])->name('staff.store');
        Route::get('staff/{idUKM}/{idStaff}', [\App\Http\Controllers\Admin\StaffController::class,'destroy'])->name('staff.destroy');


        Route::get('ukm/galleries/{id}', [\App\Http\Controllers\Admin\GalleryController::class,'index'])->name('galleries.index');
        Route::post('ukm/galleries/{id}/create', [\App\Http\Controllers\Admin\GalleryController::class,'create'])->name('galleries.create');
        Route::post('ukm/galleries/thumbnail', [\App\Http\Controllers\Admin\GalleryController::class,'image'])->name('galleries.thumbnail');
        Route::delete('ukm/galleries/selectDelete', [\App\Http\Controllers\Admin\GalleryController::class,'selectDelete'])->name('galleries.selectDelete');

    });
}
);

backend/app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;

    public function ukm(){
        return $this->belongsToMany(Ukm::class,'ukm_tags');
    }
}

backend/app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Item;
use App\Models\Tag;
use App\Models\Ukm;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        if($request->ajax()) {
//        $data = Item::orderBy('created_at','DESC')->get();
            $data = Tag::all();

//        dd($data);
            return DataTables::of($data)
                ->addColumn('action', function($data){
                    $button = '<a href="tags/'.$data->id.'/edit'.'" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>';
                    $button .= '<a  href="'.route('admin.tagsDestroy',$data->id).'" class="btn btn-danger" onclick="return confirm('.'`Are you sure?`'.')"><i class="fa fa-trash"></i> Delete</a>';
                    return $button;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('admin.dashboard.tag.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.dashboard.tag.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Tag();

        $validates = [
            'name'  =>  'required|string',
            'dsc'   =>  'required'
        ];

        $request->validate($validates);

        $data->name = $request->name;
        $data->slug = \Str::slug($request->name);
        $data->dsc = $request->dsc;

        $data->save();

        return redirect()->route('admin.tags.index')->with('success','success add UKM');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id,Request $request)
    {
        $data = Tag::findOrFail($id);
        view()->share([
            'data' => $data
        ]);
        return view('admin.dashboard.tag.edit');

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Tag::findOrFail($id);

        $validates = [
            'name'  =>  'required|string',
            'dsc'   =>  'required'
        ];

        $request->validate($validates);

        $data->name = $request->name;
        $data->slug = \Str::slug($request->name);
        $data->dsc = $request->dsc;

        $data->save();

        return redirect()->route('admin.tags.index')->with('success','edit add UKM');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
//        echo 'dqwdqw';
        $data = Tag::findOrFail($id);
        $data->delete();

        return redirect()->back()->with('danger','data has been deleted');
    }
}

backend/resources/views/admin/dashboard/tag/create.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Product</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="#">Modules</a></div>
                    <div class="breadcrumb-item">DataTables</div>
                </div>
            </div>

            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="container">
                                <div class="d-flex justify-content-between pt-5">
                                    <div>
                                        <h4>Category Item</h4>

                                    </div>
                                </div>
                            </div>

                            <div class="card-body">
                                <form action="{{route('admin.tags.store')}}" method="post">
                                    @csrf
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Name</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="name" id="name" class="form-control @error('title') is-invalid @enderror">
                                            @error('name')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>

                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Description</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="dsc" id="dsc" class="form-control @error('title') is-invalid @enderror">
                                            @error('title')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            <button class="btn btn-primary">Edit</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

backend/resources/views/admin/dashboard/tag/edit.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Product</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="#">Modules</a></div>
                    <div class="breadcrumb-item">DataTables</div>
                </div>
            </div>

            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="container">
                                <div class="d-flex justify-content-between pt-5">
                                    <div>
                                        <h4>Category Item</h4>

                                    </div>
                                </div>
                            </div>

                            <div class="card-body">
                                <form action="{{route('admin.tags.update',$data->id)}}" method="post">
                                    @csrf
                                    @method('put')
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Name</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="name" id="name" value="{{$data->name}}" class="form-control @error('title') is-invalid @enderror">
                                            @error('name')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>

                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Description</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="dsc" id="dsc"  value="{{$data->dsc}}" class="form-control @error('title') is-invalid @enderror">
                                            @error('title')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            <button class="btn btn-primary">Edit</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

backend/resources/views/admin/dashboard/tag/index.blade.php
@extends('admin.layouts.app')
@section('content')
    @include('admin.layouts.components.style-datatable')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Product</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="#">Modules</a></div>
                    <div class="breadcrumb-item">DataTables</div>
                </div>
            </div>
            @include('admin.layouts.partials.notice')

            <div class="section-body">
                <h2 class="section-title">Users</h2>

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4><a href="{{route('admin.tags.create')}}" class="btn btn-primary">TAMBAH DATA</a> </h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="item">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>dsc</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#item').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: "{{route('admin.tags.index')}}",
                },
                columns: [
                    {
                        data: 'name',
                        name: 'name'
                    },
                    {
                        data: 'dsc',
                        name: 'dsc'
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false
                    },

                ]
            });
        });
    </script>
@endsection